[
    project
]
name = "peter-parker"
version = "0.1.0"
description = "A personal assistant powered by AI. It helps you read, comment, and work with pull requests effortlessly."
authors = [
    { name = "Ali", email = "ali.khakpouri@gmail.com" }
]
dependencies = [
    "langchain==1.2.10",
    "anthropic==0.81.0",
    "python-dotenv==1.2.1",
    "pydantic==2.12.5"
]
[
    project.optional-dependencies
]
dev = [
    "pytest",
    "black",
    "flake8",
    "mypy"
]

[
tool.pytest.ini_options
]
testpaths = ["tests"]

[
tool.ruff
]
line-length = 88